from __future__ import annotations

from typing import Any

from app.core.roles import ROLE_DEFINITIONS

SYSTEM_ROLE_CODES = {role["code"] for role in ROLE_DEFINITIONS}
ROLE_METADATA_BY_CODE = {role["code"]: role for role in ROLE_DEFINITIONS}
ROLE_METADATA_FIELDS = (
    "business_roles",
    "data_scope",
    "decision_scope",
    "limitations",
    "menu_scope",
    "responsibilities",
)
ROLE_METADATA_LIST_FIELDS = {"business_roles", "limitations", "menu_scope", "responsibilities"}
ROLE_SUMMARY_SORT_COLUMNS = {
    "category": "r.category",
    "code": "lower(r.code)",
    "name": "lower(r.name)",
    "sort_order": "r.sort_order",
    "status": "r.status",
}
MENU_RESOURCE_SORT_COLUMNS = {
    "code": "lower(m.code)",
    "menu_type": "m.menu_type",
    "name": "lower(m.name)",
    "parent_code": "lower(COALESCE(parent.name, m.parent_code, ''))",
    "path": "lower(m.path)",
    "sort_order": "m.sort_order",
    "status": "m.status",
}
VALID_SCOPE_TYPES = {
    "department",
    "global",
    "knowledge_space",
    "product",
    "product_module",
    "product_version",
    "review_assignment",
    "self",
}
VALID_SCOPE_ACCESS_LEVELS = {"admin", "read", "write"}

COMPATIBILITY_MENU_RESOURCES: list[dict[str, Any]] = [
    {
        "code": "workspace.dashboard",
        "name": "团队看板",
        "path": "/welcome",
        "parent_code": None,
        "menu_type": "page",
        "sort_order": 10,
        "required_permissions": ["workspace.read"],
        "status": "active",
    },
    {
        "code": "assistant.chat",
        "name": "AI 助手",
        "path": "/assistant",
        "parent_code": None,
        "menu_type": "page",
        "sort_order": 15,
        "required_permissions": ["assistant.chat"],
        "status": "active",
    },
    {
        "code": "assistant.drafts",
        "name": "草案任务台",
        "path": "/assistant/drafts",
        "parent_code": None,
        "menu_type": "page",
        "sort_order": 16,
        "required_permissions": ["assistant.chat"],
        "status": "active",
    },
    {
        "code": "task",
        "name": "任务中心",
        "path": "/tasks",
        "parent_code": None,
        "menu_type": "group",
        "sort_order": 20,
        "required_permissions": [],
        "status": "active",
    },
    {
        "code": "task.center",
        "name": "研发任务",
        "path": "/delivery/rd-tasks",
        "parent_code": "delivery",
        "menu_type": "page",
        "sort_order": 35,
        "required_permissions": ["task.read"],
        "status": "active",
    },
    {
        "code": "delivery.rd_executor_policies",
        "name": "研发执行器策略",
        "path": "/delivery/rd-executor-policies",
        "parent_code": "delivery",
        "menu_type": "page",
        "sort_order": 34,
        "required_permissions": ["delivery.rd_executor_policies.manage"],
        "status": "active",
    },
    {
        "code": "delivery",
        "name": "需求交付",
        "path": "/delivery",
        "parent_code": None,
        "menu_type": "group",
        "sort_order": 30,
        "required_permissions": [],
        "status": "active",
    },
    {
        "code": "delivery.requirements",
        "name": "需求管理",
        "path": "/delivery/requirements",
        "parent_code": "delivery",
        "menu_type": "page",
        "sort_order": 31,
        "required_permissions": ["requirement.read"],
        "status": "active",
    },
    {
        "code": "delivery.requirement_full_chain",
        "name": "需求全链路详情",
        "path": "/delivery/requirements/:requirementId/full-chain",
        "parent_code": "delivery",
        "menu_type": "hidden_page",
        "sort_order": 32,
        "required_permissions": ["requirement.read"],
        "status": "active",
    },
    {
        "code": "delivery.versions",
        "name": "迭代版本",
        "path": "/delivery/versions",
        "parent_code": "delivery",
        "menu_type": "page",
        "sort_order": 33,
        "required_permissions": ["product.read"],
        "status": "active",
    },
    {
        "code": "delivery.bugs",
        "name": "Bug 管理",
        "path": "/delivery/bugs",
        "parent_code": "delivery",
        "menu_type": "page",
        "sort_order": 34,
        "required_permissions": ["bug.read"],
        "status": "active",
    },
    {
        "code": "product.assets",
        "name": "产品资产",
        "path": "/assets",
        "parent_code": None,
        "menu_type": "group",
        "sort_order": 40,
        "required_permissions": [],
        "status": "active",
    },
    {
        "code": "product.products",
        "name": "产品管理",
        "path": "/assets/products",
        "parent_code": "product.assets",
        "menu_type": "page",
        "sort_order": 41,
        "required_permissions": ["product.read"],
        "status": "active",
    },
    {
        "code": "knowledge.center",
        "name": "知识中心",
        "path": "/assets/knowledge",
        "parent_code": "product.assets",
        "menu_type": "page",
        "sort_order": 42,
        "required_permissions": ["knowledge.read"],
        "status": "active",
    },
    {
        "code": "knowledge.search",
        "name": "知识检索",
        "path": "/assets/knowledge",
        "parent_code": "product.assets",
        "menu_type": "hidden_page",
        "sort_order": 43,
        "required_permissions": ["knowledge.search"],
        "status": "active",
    },
    {
        "code": "governance",
        "name": "运营治理",
        "path": "/governance",
        "parent_code": None,
        "menu_type": "group",
        "sort_order": 50,
        "required_permissions": [],
        "status": "active",
    },
    {
        "code": "devops.metrics",
        "name": "日志监控",
        "path": "/governance/devops",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 51,
        "required_permissions": ["devops.read"],
        "status": "active",
    },
    {
        "code": "governance.deployments",
        "name": "运维部署",
        "path": "/governance/deployments",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 52,
        "required_permissions": ["deployment.read"],
        "status": "active",
    },
    {
        "code": "insight.center",
        "name": "用户洞察",
        "path": "/governance/insights",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 53,
        "required_permissions": ["insight.read"],
        "status": "active",
    },
    {
        "code": "audit.events",
        "name": "审计与运行",
        "path": "/governance/audit",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 54,
        "required_permissions": ["audit.read"],
        "status": "active",
    },
    {
        "code": "diagnostics.execution_traces",
        "name": "执行诊断",
        "path": "/governance/execution-traces",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 55,
        "required_permissions": ["diagnostics.execution_traces.read"],
        "status": "active",
    },
    {
        "code": "governance.worker_operations",
        "name": "Worker 运维",
        "path": "/governance/worker-operations",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 56,
        "required_permissions": ["system.settings.manage"],
        "status": "active",
    },
    {
        "code": "code_inspection.reports",
        "name": "代码巡检",
        "path": "/governance/code-inspections",
        "parent_code": "governance",
        "menu_type": "page",
        "sort_order": 57,
        "required_permissions": ["code_inspection.read"],
        "status": "active",
    },
    {
        "code": "system",
        "name": "系统管理",
        "path": "/system",
        "parent_code": None,
        "menu_type": "group",
        "sort_order": 60,
        "required_permissions": [],
        "status": "active",
    },
    {
        "code": "system.users",
        "name": "用户管理",
        "path": "/system/users",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 61,
        "required_permissions": ["system.users.manage"],
        "status": "active",
    },
    {
        "code": "system.roles",
        "name": "角色管理",
        "path": "/system/roles",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 62,
        "required_permissions": ["system.roles.manage"],
        "status": "active",
    },
    {
        "code": "system.menus",
        "name": "菜单管理",
        "path": "/system/menus",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 63,
        "required_permissions": ["system.menus.manage"],
        "status": "active",
    },
    {
        "code": "system.model_gateway",
        "name": "模型网关",
        "path": "/system/model-gateway",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 66,
        "required_permissions": ["system.model_gateway.manage"],
        "status": "active",
    },
    {
        "code": "system.health",
        "name": "系统健康",
        "path": "/system/health",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 64,
        "required_permissions": ["system.health.read"],
        "status": "active",
    },
    {
        "code": "system.settings",
        "name": "系统设置",
        "path": "/system/settings",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 65,
        "required_permissions": ["system.settings.manage"],
        "status": "active",
    },
    {
        "code": "system.execution_resources",
        "name": "执行资源授权",
        "path": "/system/execution-resources",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 69,
        "required_permissions": ["system.settings.manage"],
        "status": "active",
    },
    {
        "code": "system.assistant_action_references",
        "name": "AI助手 @ 能力",
        "path": "/system/assistant-action-references",
        "parent_code": "system",
        "menu_type": "page",
        "sort_order": 67,
        "required_permissions": ["assistant.action_references.manage"],
        "status": "active",
    },
    {
        "code": "system.scheduled_jobs",
        "name": "定时作业",
        "path": "/tasks/scheduled-jobs",
        "parent_code": "task",
        "menu_type": "page",
        "sort_order": 21,
        "required_permissions": ["system.scheduled_jobs.manage"],
        "status": "active",
    },
    {
        "code": "system.ai_capabilities",
        "name": "AI 能力配置",
        "path": "/tasks/ai-capabilities",
        "parent_code": "task",
        "menu_type": "page",
        "sort_order": 22,
        "required_permissions": ["system.ai_capabilities.manage"],
        "status": "active",
    },
    {
        "code": "system.plugins",
        "name": "插件管理",
        "path": "/tasks/plugins",
        "parent_code": "task",
        "menu_type": "page",
        "sort_order": 24,
        "required_permissions": ["system.plugins.manage"],
        "status": "active",
    },
    {
        "code": "org.departments",
        "name": "部门管理",
        "path": "/system/departments",
        "parent_code": "system",
        "menu_type": "hidden_page",
        "sort_order": 68,
        "required_permissions": ["org.department.manage"],
        "status": "active",
    },
]

COMPATIBILITY_ROLE_MENU_GRANTS: dict[str, set[str]] = {
    "admin": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.requirements",
        "delivery.requirement_full_chain",
        "delivery.rd_executor_policies",
        "delivery.versions",
        "delivery.bugs",
        "product.assets",
        "product.products",
        "knowledge.center",
        "knowledge.search",
        "governance",
        "devops.metrics",
        "governance.deployments",
        "insight.center",
        "audit.events",
        "diagnostics.execution_traces",
        "code_inspection.reports",
        "system",
        "system.users",
        "system.roles",
        "system.menus",
        "system.health",
        "system.settings",
        "system.execution_resources",
        "system.model_gateway",
        "system.assistant_action_references",
        "system.ai_capabilities",
        "system.scheduled_jobs",
        "system.plugins",
        "org.departments",
    },
    "product_owner": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.requirements",
        "delivery.requirement_full_chain",
        "delivery.versions",
        "delivery.bugs",
        "product.assets",
        "product.products",
        "knowledge.center",
        "governance",
        "governance.deployments",
        "insight.center",
        "code_inspection.reports",
    },
    "rd_owner": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.requirements",
        "delivery.rd_executor_policies",
        "delivery.bugs",
        "product.assets",
        "knowledge.center",
        "knowledge.search",
        "governance",
        "devops.metrics",
        "governance.deployments",
        "code_inspection.reports",
    },
    "reviewer": {"task", "task.center"},
    "knowledge_owner": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "product.assets",
        "knowledge.center",
        "knowledge.search",
        "governance",
        "audit.events",
    },
    "viewer": {
        "workspace.dashboard",
        "delivery",
        "delivery.requirements",
        "delivery.bugs",
        "product.assets",
        "product.products",
        "knowledge.center",
        "knowledge.search",
    },
    "developer": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.bugs",
        "product.assets",
        "knowledge.search",
    },
    "test_owner": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.bugs",
        "governance",
        "governance.deployments",
    },
    "tester": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.bugs",
        "governance",
        "governance.deployments",
    },
    "release_owner": {
        "workspace.dashboard",
        "assistant.chat",
        "assistant.drafts",
        "task",
        "task.center",
        "delivery",
        "delivery.bugs",
        "governance",
        "devops.metrics",
        "governance.deployments",
    },
}

COMPATIBILITY_ROLE_SCOPES: dict[str, list[dict[str, str]]] = {
    "admin": [{"scope_type": "global", "scope_id": "*", "access_level": "admin"}],
    "reviewer": [
        {
            "scope_type": "review_assignment",
            "scope_id": "self",
            "access_level": "write",
        }
    ],
    "test_owner": [
        {
            "scope_type": "review_assignment",
            "scope_id": "self",
            "access_level": "write",
        }
    ],
    "knowledge_owner": [
        {"scope_type": "knowledge_space", "scope_id": "*", "access_level": "admin"}
    ],
    "viewer": [{"scope_type": "self", "scope_id": "*", "access_level": "read"}],
}
